#!/bin/bash
# Generates artifacts and binaries required by plugins

# Set the 'ignore' option in all submodules to 'untracked', so that help tags aren't seen as repo changes
for s in `git submodule --quiet foreach 'echo $name'` ; do git config submodule.$s.ignore untracked ; done

# Generate helptags for bundles
vim -c 'call pathogen#helptags()' -c 'q'

# Build omnisharp server
if command -v xbuild >/dev/null 2>&1; then
	pushd bundle/omnisharp-vim/server
	xbuild
	popd
else
	echo "Warning: Program 'xbuild' not found; omnisharp server will not be built."
fi

# Install YouCompleteMe
echo "Building YouCompleteMe with:"
echo " - C-family support"
YCM_FLAGS="--clang-completer"
if command -v xbuild >/dev/null 2>&1; then
	echo " - C# support"
	YCM_FLAGS="$YCM_FLAGS --omnisharp-completer"
fi
if command -v go >/dev/null 2>&1; then
	echo " - Go support"
	YCM_FLAGS="$YCM_FLAGS --gocode-completer"
fi
if command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1; then
	echo " - JavaScript support"
	YCM_FLAGS="$YCM_FLAGS --tern-completer"
fi
if command -v rustc >/dev/null 2>&1 && command -v cargo >/dev/null 2>&1; then
	echo " - Rust support"
	YCM_FLAGS="$YCM_FLAGS --racer-completer"
fi
echo "** Note: YouCompleteMe install requires root **"
pushd bundle/YouCompleteMe
sudo ./install.py $YCM_FLAGS
popd
