#!/bin/bash
# Initial setup script for vim settings and plugins

# Check if ~/.vim should be symlinked
setupdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
vimdir="$(cd "$HOME/.vim" && pwd)"
if [ $setupdir != $vimdir ]; then
        echo "Not cloned into ~/.vim; Creating ~/.vim symlink"
        if [ -d "$HOME/.vim" ]; then
                mv "$HOME/.vim" "$HOME/.vim.orig"
                echo "Found existing ~/.vim directory; moved to ~/.vim.orig"
        fi
        ln -s $setupdir "$HOME/.vim"
        echo "Created ~/.vim symlink, pointing to" $setupdir
fi

# Create symlink to vimrc
vimrcpath="$setupdir/vimrc"
if [ -e "$HOME/.vimrc" ]; then
        mv "$HOME/.vimrc" "$HOME/.vimrc.orig"
        echo "Found existing ~/.vimrc file; moved to ~/.vimrc.orig"
fi
ln -s $vimrcpath "$HOME/.vimrc"
echo "Created ~/.vimrc symlink, pointing to" $vimrcpath

# Get plugin bundles
cd $setupdir
source ./sync-plugins
